fix(windows): do not upgrade zsh while package install is running

diff --git a/home/.chezmoiscripts/run_onchange_before_000_install-packages.sh.tmpl b/home/.chezmoiscripts/run_onchange_before_000_install-packages.sh.tmpl
--- a/home/.chezmoiscripts/run_onchange_before_000_install-packages.sh.tmpl
+++ b/home/.chezmoiscripts/run_onchange_before_000_install-packages.sh.tmpl
@@ -93,7 +93,8 @@ if ! command -v pacman >/dev/null 2>&1; then
 	echo "pacman is required for Windows packages" >&2
 	had_errors=true
 else
-	if ! pacman -Sy --needed --noconfirm \
+	# Ignore the running MSYS runtime: -Sy otherwise upgrades zsh in-place and fork fails.
+	if ! pacman -Sy --needed --noconfirm --ignore zsh,msys2-runtime,bash,pacman,filesystem \
 	    {{ template "package/args" $msysPkgs }}
 	then
 		echo "Could not install msys packages" >&2
